# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(scheme: "FastLaneTest")
    upload_to_app_store
  end


  desc "send message from slack"
  lane :slack_message do
    slack(
       message: "App successfully test.",
       success: true,
       slack_url: "https://hooks.slack.com/services/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"
       )
   end


  desc "build your iOS app"
  lane :beta do
    
    before_all do |lane|
      ENV["MATCH_PASSWORD"] = "4940"
    end

    match(type: "appstore")
    increment_build_number
    gym(scheme: "FastLaneTest")

    # upload to Testflight
    pilot

    # 都結束以後
    after_all do |lane|
      slack_message
    end
  end


end
